### ISSUE TITLE
Agec2 not working

### ISSUE THREAD

**Issue by tusharmakkar08** [tos-kamiya/agec2#1]
When I am trying to run on the sample file `ShowWeekdayR.java`, it isn't able to make `clone-indices-md.txt`. The content of `clone-indices-md.txt` is empty while `ngrams.txt` is coming same as given in test data.
##### Content of `clone-indices-md.txt`:

 # --ngram-size=6
 # --max-call-depth=-2
 # --max-method-definition=-1

It would be great if the issue can be fixed at earliest. It's working in https://github.com/tos-kamiya/agec.

**Comment by tos-kamiya** [comment]
Thanks for trying it and informing to me!
Anyway, it depends on many things including versions of vm and compiler, so I can not figure it immediately.
Also, this project has been discontinuned... sorry.

**Comment by tos-kamiya** [comment]
P.S. I am now working on another such code-clone detection for execution traces, but its target is a Python program not Java. Hopefully I will publish it near future...

**Comment by tusharmakkar08** [comment]
Great! Thanks.
